# Generated by Django 4.2.23 on 2025-06-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="采样日期"
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="现场温度"
                    ),
                ),
                (
                    "humidity",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="现场湿度"
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        blank=True,
                        choices=[("initial", "初检"), ("recheck", "复检")],
                        max_length=20,
                        verbose_name="检测类型",
                    ),
                ),
                (
                    "points_data",
                    models.JSONField(default=dict, verbose_name="点位数据"),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, verbose_name="原始API响应"),
                ),
                (
                    "confidence_score",
                    models.FloatField(blank=True, null=True, verbose_name="置信度分数"),
                ),
                (
                    "ocr_attempts",
                    models.IntegerField(default=1, verbose_name="OCR尝试次数"),
                ),
                (
                    "has_conflicts",
                    models.BooleanField(default=False, verbose_name="是否有冲突"),
                ),
                (
                    "conflict_details",
                    models.JSONField(default=dict, verbose_name="冲突详情"),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理开始时间"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.uploadedfile",
                        verbose_name="文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR结果",
                "verbose_name_plural": "OCR结果",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="联系人姓名"
                    ),
                ),
                (
                    "full_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="完整电话"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "match_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "完全匹配"),
                            ("partial", "部分匹配"),
                            ("similarity", "相似度匹配"),
                            ("manual", "手动输入"),
                        ],
                        max_length=20,
                        verbose_name="匹配类型",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(blank=True, null=True, verbose_name="相似度分数"),
                ),
                (
                    "match_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("csv", "CSV文件"),
                            ("log", "日志文件"),
                            ("manual", "手动输入"),
                        ],
                        max_length=20,
                        verbose_name="匹配来源",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "ocr_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocr.ocrresult",
                        verbose_name="OCR结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "联系人信息",
                "verbose_name_plural": "联系人信息",
            },
        ),
    ]
