# Generated by Django 4.2.23 on 2025-06-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point_name', models.CharField(max_length=100, verbose_name='点位名称')),
                ('value', models.FloatField(verbose_name='检测值')),
                ('check_type', models.CharField(choices=[('initial', '初检'), ('recheck', '复检')], max_length=20, verbose_name='检测类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrresult', verbose_name='OCR结果')),
            ],
            options={
                'verbose_name': '点位值记录',
                'verbose_name_plural': '点位值记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point_name', models.CharField(max_length=100, verbose_name='点位名称')),
                ('usage_count', models.IntegerField(default=1, verbose_name='使用次数')),
                ('total_value', models.FloatField(default=0.0, verbose_name='总值')),
                ('avg_value', models.FloatField(default=0.0, verbose_name='平均值')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
                ('initial_count', models.IntegerField(default=0, verbose_name='初检次数')),
                ('recheck_count', models.IntegerField(default=0, verbose_name='复检次数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '点位学习',
                'verbose_name_plural': '点位学习',
                'ordering': ['-usage_count', '-last_used_at'],
                'unique_together': {('point_name',)},
            },
        ),
    ]
