# Generated by Django 4.2.23 on 2025-06-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0002_pointvalue_pointlearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='match_source',
            field=models.CharField(blank=True, choices=[('customer', '客户记录'), ('log', '处理日志'), ('manual', '手动输入')], max_length=20, verbose_name='匹配来源'),
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('docx_file', models.CharField(max_length=255, verbose_name='文档文件名')),
                ('contact_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('full_phone', models.CharField(max_length=20, verbose_name='完整电话号码')),
                ('address', models.TextField(verbose_name='客户地址')),
                ('sampling_date', models.CharField(max_length=20, verbose_name='采样日期')),
                ('check_type', models.CharField(choices=[('initial', '初检'), ('recheck', '复检')], max_length=20, verbose_name='检测类型')),
                ('points_data', models.JSONField(default=dict, verbose_name='点位数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='处理状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '处理日志',
                'verbose_name_plural': '处理日志',
            },
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('full_phone', models.CharField(max_length=20, verbose_name='完整电话号码')),
                ('address', models.TextField(verbose_name='客户地址')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='合同金额')),
                ('fulfillment_time', models.DateField(blank=True, null=True, verbose_name='履约时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '客户记录',
                'verbose_name_plural': '客户记录',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='customer_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocr.customerrecord', verbose_name='关联客户记录'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='processing_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocr.processinglog', verbose_name='关联处理日志'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['full_phone'], name='ocr_process_full_ph_46a0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['contact_name'], name='ocr_process_contact_8d3226_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['sampling_date'], name='ocr_process_samplin_8dc652_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrecord',
            index=models.Index(fields=['full_phone'], name='ocr_custome_full_ph_092338_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrecord',
            index=models.Index(fields=['contact_name'], name='ocr_custome_contact_d115c5_idx'),
        ),
    ]
