# Generated by Django 4.2.23 on 2025-06-27 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0003_alter_contactinfo_match_source_processinglog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('客户姓名', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('客户电话', models.CharField(blank=True, max_length=20, verbose_name='客户电话')),
                ('客户地址', models.TextField(verbose_name='客户地址')),
                ('商品类型', models.CharField(choices=[('国标', '国标'), ('母婴', '母婴')], max_length=20, verbose_name='商品类型(国标/母婴)')),
                ('成交金额', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交金额')),
                ('面积', models.CharField(blank=True, max_length=20, verbose_name='面积')),
                ('履约时间', models.DateField(blank=True, null=True, verbose_name='履约时间')),
                ('CMA点位数量', models.CharField(blank=True, max_length=10, verbose_name='CMA点位数量')),
                ('备注赠品', models.TextField(blank=True, verbose_name='备注赠品')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'CSV记录',
                'verbose_name_plural': 'CSV记录',
            },
        ),
        migrations.RemoveField(
            model_name='processinglog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='customer_record',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='processing_log',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='match_source',
            field=models.CharField(blank=True, choices=[('csv', 'CSV记录'), ('manual', '手动输入')], max_length=20, verbose_name='匹配来源'),
        ),
        migrations.DeleteModel(
            name='CustomerRecord',
        ),
        migrations.DeleteModel(
            name='ProcessingLog',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='csv_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocr.csvrecord', verbose_name='关联CSV记录'),
        ),
        migrations.AddIndex(
            model_name='csvrecord',
            index=models.Index(fields=['客户电话'], name='ocr_csvreco_客户电话_0053ea_idx'),
        ),
        migrations.AddIndex(
            model_name='csvrecord',
            index=models.Index(fields=['客户姓名'], name='ocr_csvreco_客户姓名_5742f3_idx'),
        ),
    ]
