# Generated by Django 4.2.23 on 2025-07-17 07:36

from django.db import migrations, models
import re


def convert_gift_text_to_json(apps, schema_editor):
    """Convert existing 备注赠品 text format to JSON format"""
    CSVRecord = apps.get_model('ocr', 'CSVRecord')
    
    for record in CSVRecord.objects.all():
        if record.备注赠品 and isinstance(record.备注赠品, str):
            # Parse the old format like "{除醛宝:15;炭包:3}" to {"除醛宝": 15, "炭包": 3}
            gift_text = record.备注赠品.strip()
            if gift_text.startswith('{') and gift_text.endswith('}'):
                # Remove braces
                gift_text = gift_text[1:-1]
                gift_dict = {}
                
                # Split by semicolon and parse each item
                items = gift_text.split(';')
                for item in items:
                    if ':' in item:
                        parts = item.split(':', 1)
                        if len(parts) == 2:
                            gift_type = parts[0].strip()
                            try:
                                quantity = int(parts[1].strip())
                                gift_dict[gift_type] = quantity
                            except ValueError:
                                pass  # Skip invalid numbers
                
                # Update the record with JSON format
                record.备注赠品 = gift_dict
                record.save(update_fields=['备注赠品'])
            else:
                # If it's not in the expected format, set to empty dict
                record.备注赠品 = {}
                record.save(update_fields=['备注赠品'])


def reverse_gift_json_to_text(apps, schema_editor):
    """Reverse conversion from JSON back to text format"""
    CSVRecord = apps.get_model('ocr', 'CSVRecord')
    
    for record in CSVRecord.objects.all():
        if record.备注赠品 and isinstance(record.备注赠品, dict):
            # Convert {"除醛宝": 15, "炭包": 3} back to "{除醛宝:15;炭包:3}"
            gift_items = []
            for gift_type, quantity in record.备注赠品.items():
                gift_items.append(f"{gift_type}:{quantity}")
            
            if gift_items:
                gift_text = "{" + ";".join(gift_items) + "}"
                record.备注赠品 = gift_text
                record.save(update_fields=['备注赠品'])
            else:
                record.备注赠品 = ""
                record.save(update_fields=['备注赠品'])


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0004_drop_old_tables_create_csv"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csvrecord",
            options={"verbose_name": "订单记录", "verbose_name_plural": "订单记录"},
        ),
        migrations.AlterField(
            model_name="csvrecord",
            name="备注赠品",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='赠品信息，格式: {"除醛宝": 15, "炭包": 3}',
                verbose_name="备注赠品",
            ),
        ),
        migrations.RunPython(convert_gift_text_to_json, reverse_gift_json_to_text),
    ]
