# Generated by Django 4.2.23 on 2025-07-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="background_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="背景图片Base64数据"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="background_opacity",
            field=models.FloatField(default=0.1, verbose_name="背景图透明度"),
        ),
    ]
