# Generated by Django 4.2.23 on 2025-06-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_message", models.TextField(verbose_name="原始微信消息")),
                (
                    "formatted_csv",
                    models.TextField(blank=True, verbose_name="格式化后的CSV"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("submitted", "已提交"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "github_file_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="GitHub文件路径"
                    ),
                ),
                (
                    "github_commit_sha",
                    models.CharField(blank=True, max_length=40, verbose_name="提交SHA"),
                ),
                (
                    "github_commit_url",
                    models.URLField(blank=True, verbose_name="提交URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理历史",
                "verbose_name_plural": "处理历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=False, verbose_name="是否有效"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="错误信息"),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="警告信息"),
                ),
                (
                    "duplicate_indexes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="重复项索引"
                    ),
                ),
                (
                    "match_details",
                    models.JSONField(blank=True, default=list, verbose_name="匹配详情"),
                ),
                (
                    "format_fixes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="格式修正信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processing_history",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="wechat_csv.processinghistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "验证结果",
                "verbose_name_plural": "验证结果",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="尝试次数"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="是否锁定"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="锁定到"),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(auto_now=True, verbose_name="最后尝试时间"),
                ),
            ],
            options={
                "verbose_name": "登录尝试",
                "verbose_name_plural": "登录尝试",
                "unique_together": {("ip_address",)},
            },
        ),
        migrations.CreateModel(
            name="WechatCsvRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="客户姓名"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="客户电话"
                    ),
                ),
                ("customer_address", models.TextField(verbose_name="客户地址")),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=[("国标", "国标"), ("母婴", "母婴")],
                        max_length=20,
                        verbose_name="商品类型",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="成交金额",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="面积",
                    ),
                ),
                (
                    "fulfillment_date",
                    models.DateField(blank=True, null=True, verbose_name="履约时间"),
                ),
                (
                    "cma_points",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="CMA点位数量"
                    ),
                ),
                (
                    "gift_notes",
                    models.TextField(
                        blank=True,
                        help_text="格式：{品类:数量}",
                        verbose_name="备注赠品",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "processing_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="wechat_csv.processinghistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV记录",
                "verbose_name_plural": "CSV记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_phone"], name="wechat_csv__custome_94352d_idx"
                    ),
                    models.Index(
                        fields=["customer_name", "customer_address"],
                        name="wechat_csv__custome_2e2437_idx",
                    ),
                    models.Index(
                        fields=["fulfillment_date"],
                        name="wechat_csv__fulfill_f7a684_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="wechat_csv__created_208de5_idx"
                    ),
                ],
            },
        ),
    ]
