# Generated by Django 4.2.23 on 2025-06-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "uniform_profit_rate",
                    models.BooleanField(default=False, verbose_name="统一分润比"),
                ),
                (
                    "profit_rate_value",
                    models.FloatField(default=0.05, verbose_name="分润比值"),
                ),
                (
                    "medicine_cost_per_order",
                    models.FloatField(default=120.1, verbose_name="每单药水成本"),
                ),
                (
                    "cma_cost_per_point",
                    models.FloatField(default=60.0, verbose_name="每个CMA点位成本"),
                ),
                (
                    "config_options",
                    models.JSONField(default=dict, verbose_name="其他配置选项"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否为默认配置"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "月度报表配置",
                "verbose_name_plural": "月度报表配置",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="报表标题")),
                ("report_month", models.DateField(verbose_name="报表月份")),
                (
                    "config_data",
                    models.JSONField(default=dict, verbose_name="配置数据"),
                ),
                (
                    "summary_data",
                    models.JSONField(default=dict, verbose_name="汇总统计"),
                ),
                (
                    "address_matches",
                    models.JSONField(default=dict, verbose_name="地址匹配结果"),
                ),
                (
                    "cost_analysis",
                    models.JSONField(default=dict, verbose_name="成本分析"),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="monthly/excel/%Y/%m/",
                        verbose_name="Excel文件",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="monthly/pdf/%Y/%m/",
                        verbose_name="PDF文件",
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="是否已生成"),
                ),
                (
                    "generation_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生成完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports_csv",
                        to="files.uploadedfile",
                        verbose_name="CSV文件",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports_log",
                        to="files.uploadedfile",
                        verbose_name="日志文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "月度报表",
                "verbose_name_plural": "月度报表",
                "ordering": ["-report_month", "-created_at"],
            },
        ),
    ]
