# Generated by Django 4.2.23 on 2025-06-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('monthly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='csv_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports_csv', to='files.uploadedfile', verbose_name='CSV文件'),
        ),
    ]
