# Generated by Django 4.2.23 on 2025-06-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchFileItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "processing_order",
                    models.IntegerField(default=0, verbose_name="处理顺序"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理耗时(秒)"
                    ),
                ),
            ],
            options={
                "verbose_name": "批量文件项",
                "verbose_name_plural": "批量文件项",
                "ordering": ["processing_order"],
            },
        ),
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_files",
                    models.IntegerField(default=0, verbose_name="总文件数"),
                ),
                (
                    "processed_files",
                    models.IntegerField(default=0, verbose_name="已处理文件数"),
                ),
                (
                    "failed_files",
                    models.IntegerField(default=0, verbose_name="失败文件数"),
                ),
                ("settings", models.JSONField(default=dict, verbose_name="处理设置")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "estimated_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预计完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "uploaded_files",
                    models.ManyToManyField(
                        through="batch.BatchFileItem",
                        to="files.uploadedfile",
                        verbose_name="上传文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量任务",
                "verbose_name_plural": "批量任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="batchfileitem",
            name="batch_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="batch.batchjob",
                verbose_name="批量任务",
            ),
        ),
        migrations.AddField(
            model_name="batchfileitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="batchfileitem",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="files.uploadedfile",
                verbose_name="文件",
            ),
        ),
        migrations.AddField(
            model_name="batchfileitem",
            name="ocr_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ocr.ocrresult",
                verbose_name="OCR结果",
            ),
        ),
    ]
