# Generated by Django 4.2.23 on 2025-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
