# Generated by Django 4.2.23 on 2025-07-17 02:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="用于识别的配置名称",
                        max_length=100,
                        verbose_name="配置名称",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic Claude"),
                            ("custom", "自定义服务"),
                        ],
                        max_length=20,
                        verbose_name="服务提供商",
                    ),
                ),
                (
                    "api_format",
                    models.CharField(
                        choices=[("gemini", "Gemini格式"), ("openai", "OpenAI格式")],
                        help_text="API调用格式（Gemini格式或OpenAI格式）",
                        max_length=20,
                        verbose_name="API格式",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        help_text="API服务的基础URL",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="API基础URL",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API访问密钥，将被加密存储",
                        max_length=500,
                        verbose_name="API密钥",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="使用的AI模型名称",
                        max_length=100,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30, verbose_name="超时时间（秒）"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(default=3, verbose_name="最大重试次数"),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="其他配置参数，JSON格式",
                        verbose_name="额外配置",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否为默认配置"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="数值越小优先级越高，用于故障切换",
                        verbose_name="优先级",
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功调用次数"),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败调用次数"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后测试时间"
                    ),
                ),
                (
                    "last_test_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="最后测试结果"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI服务配置",
                "verbose_name_plural": "AI服务配置",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIConfigHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("test", "测试"),
                            ("activate", "激活"),
                            ("deactivate", "停用"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前数据"),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更后数据"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="ai_config.aiserviceconfig",
                        verbose_name="配置",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_config_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI配置变更历史",
                "verbose_name_plural": "AI配置变更历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIServiceUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="OCR、订单处理等",
                        max_length=50,
                        verbose_name="服务类型",
                    ),
                ),
                ("request_data", models.JSONField(verbose_name="请求数据")),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="响应数据"),
                ),
                ("is_success", models.BooleanField(verbose_name="是否成功")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="响应时间（毫秒）"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="ai_config.aiserviceconfig",
                        verbose_name="使用的配置",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI服务使用日志",
                "verbose_name_plural": "AI服务使用日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["config", "-created_at"],
                        name="ai_config_a_config__5984d1_idx",
                    ),
                    models.Index(
                        fields=["service_type", "-created_at"],
                        name="ai_config_a_service_d171ce_idx",
                    ),
                    models.Index(
                        fields=["is_success", "-created_at"],
                        name="ai_config_a_is_succ_8fb64e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aiserviceconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_config",
            ),
        ),
    ]
