# Generated by Django 4.2.23 on 2025-06-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "template_file",
                    models.FileField(upload_to="templates/", verbose_name="模板文件"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "template_config",
                    models.JSONField(default=dict, verbose_name="模板配置"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告模板",
                "verbose_name_plural": "报告模板",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("detection", "检测报告"), ("monthly", "月度报表")],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="报告标题")),
                (
                    "form_data",
                    models.JSONField(default=dict, verbose_name="表单填写数据"),
                ),
                (
                    "template_data",
                    models.JSONField(default=dict, verbose_name="模板渲染数据"),
                ),
                (
                    "docx_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/docx/%Y/%m/",
                        verbose_name="Word文件",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/pdf/%Y/%m/",
                        verbose_name="PDF文件",
                    ),
                ),
                (
                    "delete_original_docx",
                    models.BooleanField(default=True, verbose_name="删除原始Word文件"),
                ),
                (
                    "generation_settings",
                    models.JSONField(default=dict, verbose_name="生成设置"),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="是否已生成"),
                ),
                (
                    "generation_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生成开始时间"
                    ),
                ),
                (
                    "generation_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生成完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocr.ocrresult",
                        verbose_name="OCR结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告",
                "verbose_name_plural": "报告",
                "ordering": ["-created_at"],
            },
        ),
    ]
