# Generated by Django 4.2.23 on 2025-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='delete_original_docx',
            field=models.BooleanField(default=False, verbose_name='删除原始Word文件'),
        ),
    ]
