# Generated by Django 4.2.23 on 2025-06-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="文件"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME类型"),
                ),
                (
                    "hash_md5",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="MD5哈希"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
                "ordering": ["-created_at"],
            },
        ),
    ]
