# Generated by Django 4.2.23 on 2025-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="hash_md5",
            field=models.CharField(max_length=32, verbose_name="MD5哈希"),
        ),
    ]
